import SidebarNav from '@/components/SidebarNav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full h-full p-4 relative">
          <div className='flex min-w-[1024px] relative'>
            <SidebarNav />
            <main className='ml-[300px] flex flex-wrap relative'>
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
